<?php require '../../pagxkapo.php' ?>

<h1>Bardo</h1>
<table>
<tr>
<th rowspan="2">Nivelo</th>
<th rowspan="2">BAB</th>
<th rowspan="2">REF</th>
<th rowspan="2">VOL</th>
<th rowspan="2">PER</th>
<th rowspan="2">Speciala</th>
<th class="sen-sub-linio" colspan="6">Sorĉoj po tago</th>
</tr>
<tr>
    <th>1a</th>
    <th>2a</th>
    <th>3a</th>
    <th>4a</th>
    <th>5a</th>
    <th>6a</th>
</tr>
<tr>
    <td>1</td>
    <td>+0</td>
    <td>+2</td>
    <td>+2</td>
    <td>+0</td>
    <td><a href="#Deflankigi">Deflankigi</a>, <a href="#Anatemkanto">Anatemkanto</a>, <a href="#Bardoprezentado">Bardoprezentado</a>, <a href="#Bardoscio">Bardoscio</a>, <a href="#Allogi">Allogi</a>, <a href="#Kanto-de-kuragxo">Kanto de kuraĝo +1</a>, <a href="#Artifikoj">Artifikoj</a></td>
    <td>1</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
</tr>
<tr>
    <td>2</td>
    <td>+1</td>
    <td>+3</td>
    <td>+3</td>
    <td>+0</td>
    <td><a href="#Sperta">Sperta</a>, <a href="#Multflanka-prezento">Multflanka prezento</a></td>
    <td>2</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
</tr>
<tr>
    <td>3</td>
    <td>+2</td>
    <td>+3</td>
    <td>+3</td>
    <td>+1</td>
    <td><a href="#Kanto-de-sukceso">Kanto de sukceso +2</a></td>
    <td>3</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
</tr>
<tr>
    <td>4</td>
    <td>+3</td>
    <td>+4</td>
    <td>+4</td>
    <td>+1</td>
    <td>-</td>
    <td>3</td>
    <td>1</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
</tr>
<tr>
    <td>5</td>
    <td>+3</td>
    <td>+4</td>
    <td>+4</td>
    <td>+1</td>
    <td><a href="#Sciulo">Sciulo 1/ Tag</a>, <a href="#Kanto-de-kuragxo">Kanto de kuraĝo +2</a></td>
    <td>4</td>
    <td>2</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
</tr>
<tr>
    <td>6</td>
    <td>+4</td>
    <td>+5</td>
    <td>+5</td>
    <td>+2</td>
    <td><a href="#Suflori">Suflori</a>, <a href="#Multflanka-prezento">Multflanka prezento</a></td>
    <td>4</td>
    <td>3</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
</tr>
<tr>
    <td>7</td>
    <td>+5</td>
    <td>+5</td>
    <td>+5</td>
    <td>+2</td>
    <td><a href="#Kanto-de-sukceso">Kanto de sukceso +3</a></td>
    <td>4</td>
    <td>3</td>
    <td>1</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
</tr>
<tr>
    <td>8</td>
    <td>+6/+1</td>
    <td>+6</td>
    <td>+6</td>
    <td>+2</td>
    <td><a href="#Lamentokanto">Lamentokanto</a></td>
    <td>4</td>
    <td>4</td>
    <td>2</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
</tr>
<tr>
    <td>9</td>
    <td>+6/+1</td>
    <td>+6</td>
    <td>+6</td>
    <td>+3</td>
    <td><a href="#Kanto-de-grando">Kanto de grando</a></td>
    <td>5</td>
    <td>4</td>
    <td>3</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
</tr>
<tr>
    <td>10</td>
    <td>+7/+2</td>
    <td>+7</td>
    <td>+7</td>
    <td>+3</td>
    <td><a href="#Multtalentulo">Multtalentulo</a>, <a href="#Multflanka-prezento">Multflanka prezento</a></td>
    <td>5</td>
    <td>4</td>
    <td>3</td>
    <td>1</td>
    <td>-</td>
    <td>-</td>
</tr>
<tr>
    <td>11</td>
    <td>+8/+3</td>
    <td>+7</td>
    <td>+7</td>
    <td>+3</td>
    <td><a href="#Sciulo"> Sciulo 2/ Tag</a>, <a href="#Kanto-de-sukceso">Kanto de sukceso +4</a>, <a href="#Kanto-de-kuragxo">Kanto de kuraĝo +3</a></td>
    <td>5</td>
    <td>4</td>
    <td>4</td>
    <td>2</td>
    <td>-</td>
    <td>-</td>
</tr>
<tr>
    <td>12</td>
    <td>+9/+4</td>
    <td>+8</td>
    <td>+8</td>
    <td>+4</td>
    <td><a href="#Refresxiganta-prezento">Refreŝiganta prezento</a></td>
    <td>5</td>
    <td>5</td>
    <td>4</td>
    <td>3</td>
    <td>-</td>
    <td>-</td>
</tr>
<tr>
    <td>13</td>
    <td>+9/+4</td>
    <td>+8</td>
    <td>+8</td>
    <td>+4</td>
    <td>-</td>
    <td>5</td>
    <td>5</td>
    <td>4</td>
    <td>3</td>
    <td>1</td>
    <td>-</td>
</tr>
<tr>
    <td>14</td>
    <td>+10/+5</td>
    <td>+9</td>
    <td>+9</td>
    <td>+4</td>
    <td><a href="#Kanto-de-timigo">Kanto de timigo</a>, <a href="#Multflanka-prezento">Multflanka prezento</a></td>
    <td>5</td>
    <td>5</td>
    <td>4</td>
    <td>4</td>
    <td>2</td>
    <td>-</td>
</tr>
<tr>
    <td>15</td>
    <td>+11/+6/+1</td>
    <td>+9</td>
    <td>+9</td>
    <td>+5</td>
    <td><a href="#Kanto-de-sukceso">Kanto de sukceso +5</a>, <a href="#Kanto-de-herokuragxo">Kanto de herokuraĝo</a></td>
    <td>5</td>
    <td>5</td>
    <td>5</td>
    <td>4</td>
    <td>3</td>
    <td>-</td>
</tr>
<tr>
    <td>16</td>
    <td>+12/+7/+2</td>
    <td>+10</td>
    <td>+10</td>
    <td>+5</td>
    <td>-</td>
    <td>5</td>
    <td>5</td>
    <td>5</td>
    <td>4</td>
    <td>3</td>
    <td>1</td>
</tr>
<tr>
    <td>17</td>
    <td>+12/+7/+2</td>
    <td>+10</td>
    <td>+10</td>
    <td>+5</td>
    <td><a href="#Sciulo"> Sciulo 3/ Tag</a>, <a href="#Kanto-de-kuragxo">Kanto de kuraĝo +4</a></td>
    <td>5</td>
    <td>5</td>
    <td>5</td>
    <td>4</td>
    <td>4</td>
    <td>2</td>
</tr>
<tr>
    <td>18</td>
    <td>+13/+8/+3</td>
    <td>+11</td>
    <td>+11</td>
    <td>+6</td>
    <td><a href="#Amassuflori">Amassuflori</a>, <a href="#Multflanka-prezento">Multflanka prezento</a></td>
    <td>5</td>
    <td>5</td>
    <td>5</td>
    <td>5</td>
    <td>4</td>
    <td>3</td>
</tr>
<tr>
    <td>19</td>
    <td>+14/+9/+4</td>
    <td>+11</td>
    <td>+11</td>
    <td>+6</td>
    <td><a href="#Kanto-de-sukceso">Kanto de sukceso +6</a></td>
    <td>5</td>
    <td>5</td>
    <td>5</td>
    <td>5</td>
    <td>5</td>
    <td>4</td>
</tr>
<tr>
    <td>20</td>
    <td>+15/+10/+5</td>
    <td>+12</td>
    <td>+12</td>
    <td>+6</td>
    <td><a href="#Mortiga-melodio">Mortiga melodio</a></td>
    <td>5</td>
    <td>5</td>
    <td>5</td>
    <td>5</td>
    <td>5</td>
    <td>5</td>
</tr>
</table>

<?php require '../../pagxpiedo.php' ?>

