<?php require '../../pagxkapo.php' ?>

<title>Druido</title>

<p><b>Pensmaniero:</b> neŭtrala bona, laŭleĝa neŭtrala, neŭtrala, ĥaosa neŭtrala aŭ neŭtrala malbona</p>
<p><b>Vivkubetoj:</b> k8</p>
<p><b>Oro je la komenco:</b> 2k6 &times; 10mo (mezkvanta 70mo)
<p><b>Klaskapablecoj:</b> Grimpi&nbsp;(FOR), Flugi&nbsp;(LER), Interrilati&nbsp;kun&nbsp;bestoj&nbsp;(KAR), Kuraci&nbsp;(SAĜ), Metio&nbsp;(INT), Naĝi&nbsp;(FOR), Percepto&nbsp;(SAĜ), Profesio&nbsp;(SAĜ), Rajdi&nbsp;(LER), Scio&nbsp;(geografio)&nbsp;(INT), Scio&nbsp;(naturo)&nbsp;(INT), Sorĉkono&nbsp;(INT), Transvivado&nbsp;(SAĜ)
<p><b>Kapablecpoentoj po nivelo:</b> 4 + INT-modifilo

<table>
    <caption>Tabelo: Druido</caption>
    <tr>
        <th rowspan="2">Nivelo</th>
        <th rowspan="2">BAB</th>
        <th rowspan="2">REF</th>
        <th rowspan="2">VOL</th>
        <th rowspan="2">PER</th>
        <th rowspan="2">Speciala</th>
        <th class="sen-sub-linio" colspan="10">Sorĉoj po tago</th>
    </tr>
    <tr>
        <th>0a</th>
        <th>1a</th>
        <th>2a</th>
        <th>3a</th>
        <th>4a</th>
        <th>5a</th>
        <th>6a</th>
        <th>7a</th>
        <th>8a</th>
        <th>9a</th>
    </tr>
    <tr>
        <td>1</td>
        <td>+0</td>
        <td>+0</td>
        <td>+2</td>
        <td>+2</td>
        <td><a href="#Bund-mit-der-Natur">Bund mit der Natur</a>, <a href="#Naturgespür">Naturgespür</a>, <a href="#Gebete">Gebete</a>, <a href="#Tierempathie">Tierempathie</a></td>
        <td>3</td>
        <td>1</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
    </tr>
    <tr>
        <td>2</td>
        <td>+1</td>
        <td>+0</td>
        <td>+3</td>
        <td>+3</td>
        <td><a href="#Unterholz-durchqueren">Unterholz durchqueren</a></td>
        <td>4</td>
        <td>2</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
    </tr>
    <tr>
        <td>3</td>
        <td>+2</td>
        <td>+1</td>
        <td>+3</td>
        <td>+3</td>
        <td><a href="#Spurloser-Schritt">Spurloser Schritt</a></td>
        <td>4</td>
        <td>2</td>
        <td>1</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
    </tr>
    <tr>
        <td>4</td>
        <td>+3</td>
        <td>+1</td>
        <td>+4</td>
        <td>+4</td>
        <td><a href="#Lockruf-der-Natur-widerstehen">Lockruf der Natur widerstehen</a>, <a href="#Tiergestalt">Tiergestalt (1/ Tag)</a></td>
        <td>4</td>
        <td>3</td>
        <td>2</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
    </tr>
    <tr>
        <td>5</td>
        <td>+3</td>
        <td>+1</td>
        <td>+4</td>
        <td>+4</td>
        <td>-</td>
        <td>4</td>
        <td>3</td>
        <td>2</td>
        <td>1</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
    </tr>
    <tr>
        <td>6</td>
        <td>+4</td>
        <td>+2</td>
        <td>+5</td>
        <td>+5</td>
        <td><a href="#Tiergestalt">Tiergestalt (2/ Tag)</a></td>
        <td>4</td>
        <td>3</td>
        <td>3</td>
        <td>2</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
    </tr>
    <tr>
        <td>7</td>
        <td>+5</td>
        <td>+2</td>
        <td>+5</td>
        <td>+5</td>
        <td>-</td>
        <td>4</td>
        <td>4</td>
        <td>3</td>
        <td>2</td>
        <td>1</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
    </tr>
    <tr>
        <td>8</td>
        <td>+6/+1</td>
        <td>+2</td>
        <td>+6</td>
        <td>+6</td>
        <td><a href="#Tiergestalt">Tiergestalt (3/ Tag)</a></td>
        <td>4</td>
        <td>4</td>
        <td>3</td>
        <td>3</td>
        <td>2</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
    </tr>
    <tr>
        <td>9</td>
        <td>+6/+1</td>
        <td>+3</td>
        <td>+6</td>
        <td>+6</td>
        <td><a href="#Immunität-gegen-Gifte">Immunität gegen Gift</a></td>
        <td>4</td>
        <td>4</td>
        <td>4</td>
        <td>3</td>
        <td>2</td>
        <td>1</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
    </tr>
    <tr>
        <td>10</td>
        <td>+7/+2</td>
        <td>+3</td>
        <td>+7</td>
        <td>+7</td>
        <td><a href="#Tiergestalt">Tiergestalt (4/ Tag)</a></td>
        <td>4</td>
        <td>4</td>
        <td>4</td>
        <td>3</td>
        <td>3</td>
        <td>2</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
    </tr>
    <tr>
        <td>11</td>
        <td>+8/+3</td>
        <td>+3</td>
        <td>+7</td>
        <td>+7</td>
        <td>-</td>
        <td>4</td>
        <td>4</td>
        <td>4</td>
        <td>4</td>
        <td>3</td>
        <td>2</td>
        <td>1</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
    </tr>
    <tr>
        <td>12</td>
        <td>+9/+4</td>
        <td>+4</td>
        <td>+8</td>
        <td>+8</td>
        <td><a href="#Tiergestalt">Tiergestalt (5/ Tag)</a></td>
        <td>4</td>
        <td>4</td>
        <td>4</td>
        <td>4</td>
        <td>3</td>
        <td>3</td>
        <td>2</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
    </tr>
    <tr>
        <td>13</td>
        <td>+9/+4</td>
        <td>+4</td>
        <td>+8</td>
        <td>+8</td>
        <td><a href="#Tausend-Gesichter">Tausend Gesichter</a></td>
        <td>4</td>
        <td>4</td>
        <td>4</td>
        <td>4</td>
        <td>4</td>
        <td>3</td>
        <td>2</td>
        <td>1</td>
        <td>-</td>
        <td>-</td>
    </tr>
    <tr>
        <td>14</td>
        <td>+10/+5</td>
        <td>+4</td>
        <td>+9</td>
        <td>+9</td>
        <td><a href="#Tiergestalt">Tiergestalt (6/ Tag)</a></td>
        <td>4</td>
        <td>4</td>
        <td>4</td>
        <td>4</td>
        <td>4</td>
        <td>3</td>
        <td>3</td>
        <td>2</td>
        <td>-</td>
        <td>-</td>
    </tr>
    <tr>
        <td>15</td>
        <td>+11/+6/+1</td>
        <td>+5</td>
        <td>+9</td>
        <td>+9</td>
        <td><a href="#Zeitloser-Körper">Zeitloser Körper</a></td>
        <td>4</td>
        <td>4</td>
        <td>4</td>
        <td>4</td>
        <td>4</td>
        <td>4</td>
        <td>3</td>
        <td>2</td>
        <td>1</td>
        <td>-</td>
    </tr>
    <tr>
        <td>16</td>
        <td>+12/+7/+2</td>
        <td>+5</td>
        <td>+10</td>
        <td>+10</td>
        <td><a href="#Tiergestalt">Tiergestalt (7/ Tag)</a></td>
        <td>4</td>
        <td>4</td>
        <td>4</td>
        <td>4</td>
        <td>4</td>
        <td>4</td>
        <td>3</td>
        <td>3</td>
        <td>2</td>
        <td>-</td>
    </tr>
    <tr>
        <td>17</td>
        <td>+12/+7/+2</td>
        <td>+5</td>
        <td>+10</td>
        <td>+10</td>
        <td>-</td>
        <td>4</td>
        <td>4</td>
        <td>4</td>
        <td>4</td>
        <td>4</td>
        <td>4</td>
        <td>4</td>
        <td>3</td>
        <td>2</td>
        <td>1</td>
    </tr>
    <tr>
        <td>18</td>
        <td>+13/+8/+3</td>
        <td>+6</td>
        <td>+11</td>
        <td>+11</td>
        <td><a href="#Tiergestalt">Tiergestalt (8/ Tag)</a></td>
        <td>4</td>
        <td>4</td>
        <td>4</td>
        <td>4</td>
        <td>4</td>
        <td>4</td>
        <td>4</td>
        <td>3</td>
        <td>3</td>
        <td>2</td>
    </tr>
    <tr>
        <td>19</td>
        <td>+14/+9/+4</td>
        <td>+6</td>
        <td>+11</td>
        <td>+11</td>
        <td>-</td>
        <td>4</td>
        <td>4</td>
        <td>4</td>
        <td>4</td>
        <td>4</td>
        <td>4</td>
        <td>4</td>
        <td>4</td>
        <td>3</td>
        <td>3</td>
    </tr>
    <tr>
        <td>20</td>
        <td>+15/+10/+5</td>
        <td>+6</td>
        <td>+12</td>
        <td>+12</td>
        <td><a href="#Tiergestalt">Tiergestalt (beliebig)</a></td>
        <td>4</td>
        <td>4</td>
        <td>4</td>
        <td>4</td>
        <td>4</td>
        <td>4</td>
        <td>4</td>
        <td>4</td>
        <td>4</td>
        <td>4</td>
    </tr>
</table>

<?php require '../../pagxpiedo.php' ?>

