<?php require '../../pagxkapo.php' ?>

<title>Kleriko</title>

<p><b>Pensmaniero:</b> La pensmaniero de la kleriko nur rajtas devii unu paŝon de la pensmaniero de lia dio. Do ĝi rajtas diferenci unu paŝon sur unu el la du aksoj (ĥaosa-laŭleĝa aŭ bona-malbona).</p>
<p><b>Vivkubetoj:</b> k8</p>
<p><b>Oro je la komenco:</b> 4k6 &times; 10mo (mezkvanta 140mo)
<p><b>Klaskapablecoj:</b> Diplomatio&nbsp;(KAR), Ekkoni&nbsp;motivon&nbsp;(SAĜ), Kuraci&nbsp;(SAĜ), Lingvoscio&nbsp;(INT), Metio&nbsp;(INT), Profesio&nbsp;(SAĜ), Scio&nbsp;(arkano)&nbsp;(INT), Scio&nbsp;(la ebenoj)&nbsp;(INT), Scio&nbsp;(historio)&nbsp;(INT), Scio&nbsp;(nobeleco)&nbsp;(INT), Scio&nbsp;(religio)&nbsp;(INT), Sorĉkono&nbsp;(INT), Taksi&nbsp;(INT)
<p><b>Kapablecpoentoj po nivelo:</b> 2 + INT-modifilo

<table>
    <caption>Tabelo: Kleriko</caption>
    <tr>
        <th rowspan="2">Nivelo</th>
        <th rowspan="2">BAB</th>
        <th rowspan="2">REF</th>
        <th rowspan="2">VOL</th>
        <th rowspan="2">PER</th>
        <th rowspan="2">Speciala</th>
        <th class="sen-sub-linio" colspan="10">Sorĉoj po tago</th>
    </tr>
    <tr>
        <th>0a</th>
        <th>1a</th>
        <th>2a</th>
        <th>3a</th>
        <th>4a</th>
        <th>5a</th>
        <th>6a</th>
        <th>7a</th>
        <th>8a</th>
        <th>9a</th>
    </tr>
    <tr>
        <td>1</td>
        <td>+0</td>
        <td>+0</td>
        <td>+2</td>
        <td>+2</td>
        <td><a href="#Aura">Aura</a>, <a href="#Domänen-Merkmal">Domänen</a>, <a href="#Gebete">Gebete</a>, <a href="#Energie-fokussieren">Energie fokussieren 1W6</a></td>
        <td>3</td>
        <td>1+1</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
    </tr>
    <tr>
        <td>2</td>
        <td>+1</td>
        <td>+0</td>
        <td>+3</td>
        <td>+3</td>
        <td>-</td>
        <td>4</td>
        <td>2+1</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
    </tr>
    <tr>
        <td>3</td>
        <td>+2</td>
        <td>+1</td>
        <td>+3</td>
        <td>+3</td>
        <td><a href="#Energie-fokussieren">Energie fokussieren 2W6</a></td>
        <td>4</td>
        <td>2+1</td>
        <td>1+1</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
    </tr>
    <tr>
        <td>4</td>
        <td>+3</td>
        <td>+1</td>
        <td>+4</td>
        <td>+4</td>
        <td>-</td>
        <td>4</td>
        <td>3+1</td>
        <td>2+1</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
    </tr>
    <tr>
        <td>5</td>
        <td>+3</td>
        <td>+1</td>
        <td>+4</td>
        <td>+4</td>
        <td><a href="#Energie-fokussieren">Energie fokussieren 3W6</a></td>
        <td>4</td>
        <td>3+1</td>
        <td>2+1</td>
        <td>1+1</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
    </tr>
    <tr>
        <td>6</td>
        <td>+4</td>
        <td>+2</td>
        <td>+5</td>
        <td>+5</td>
        <td>-</td>
        <td>4</td>
        <td>3+1</td>
        <td>3+1</td>
        <td>2+1</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
    </tr>
    <tr>
        <td>7</td>
        <td>+5</td>
        <td>+2</td>
        <td>+5</td>
        <td>+5</td>
        <td><a href="#Energie-fokussieren">Energie fokussieren 4W6</a></td>
        <td>4</td>
        <td>4+1</td>
        <td>3+1</td>
        <td>2+1</td>
        <td>1+1</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
    </tr>
    <tr>
        <td>8</td>
        <td>+6/+1</td>
        <td>+2</td>
        <td>+6</td>
        <td>+6</td>
        <td>-</td>
        <td>4</td>
        <td>4+1</td>
        <td>3+1</td>
        <td>3+1</td>
        <td>2+1</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
    </tr>
    <tr>
        <td>9</td>
        <td>+6/+1</td>
        <td>+3</td>
        <td>+6</td>
        <td>+6</td>
        <td><a href="#Energie-fokussieren">Energie fokussieren 5W6</a></td>
        <td>4</td>
        <td>4+1</td>
        <td>4+1</td>
        <td>3+1</td>
        <td>2+1</td>
        <td>1+1</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
    </tr>
    <tr>
        <td>10</td>
        <td>+7/+2</td>
        <td>+3</td>
        <td>+7</td>
        <td>+7</td>
        <td>-</td>
        <td>4</td>
        <td>4+1</td>
        <td>4+1</td>
        <td>3+1</td>
        <td>3+1</td>
        <td>2+1</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
    </tr>
    <tr>
        <td>11</td>
        <td>+8/+3</td>
        <td>+3</td>
        <td>+7</td>
        <td>+7</td>
        <td><a href="#Energie-fokussieren">Energie fokussieren 6W6</a></td>
        <td>4</td>
        <td>4+1</td>
        <td>4+1</td>
        <td>4+1</td>
        <td>3+1</td>
        <td>2+1</td>
        <td>1+1</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
    </tr>
    <tr>
        <td>12</td>
        <td>+9/+4</td>
        <td>+4</td>
        <td>+8</td>
        <td>+8</td>
        <td>-</td>
        <td>4</td>
        <td>4+1</td>
        <td>4+1</td>
        <td>4+1</td>
        <td>3+1</td>
        <td>3+1</td>
        <td>2+1</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
    </tr>
    <tr>
        <td>13</td>
        <td>+9/+4</td>
        <td>+4</td>
        <td>+8</td>
        <td>+8</td>
        <td><a href="#Energie-fokussieren">Energie fokussieren 7W6</a></td>
        <td>4</td>
        <td>4+1</td>
        <td>4+1</td>
        <td>4+1</td>
        <td>4+1</td>
        <td>3+1</td>
        <td>2+1</td>
        <td>1+1</td>
        <td>-</td>
        <td>-</td>
    </tr>
    <tr>
        <td>14</td>
        <td>+10/+5</td>
        <td>+4</td>
        <td>+9</td>
        <td>+9</td>
        <td>-</td>
        <td>4</td>
        <td>4+1</td>
        <td>4+1</td>
        <td>4+1</td>
        <td>4+1</td>
        <td>3+1</td>
        <td>3+1</td>
        <td>2+1</td>
        <td>-</td>
        <td>-</td>
    </tr>
    <tr>
        <td>15</td>
        <td>+11/+6/+1</td>
        <td>+5</td>
        <td>+9</td>
        <td>+9</td>
        <td><a href="#Energie-fokussieren">Energie fokussieren 8W6</a></td>
        <td>4</td>
        <td>4+1</td>
        <td>4+1</td>
        <td>4+1</td>
        <td>4+1</td>
        <td>4+1</td>
        <td>3+1</td>
        <td>2+1</td>
        <td>1+1</td>
        <td>-</td>
    </tr>
    <tr>
        <td>16</td>
        <td>+12/+7/+2</td>
        <td>+5</td>
        <td>+10</td>
        <td>+10</td>
        <td>-</td>
        <td>4</td>
        <td>4+1</td>
        <td>4+1</td>
        <td>4+1</td>
        <td>4+1</td>
        <td>4+1</td>
        <td>3+1</td>
        <td>3+1</td>
        <td>2+1</td>
        <td>-</td>
    </tr>
    <tr>
        <td>17</td>
        <td>+12/+7/+2</td>
        <td>+5</td>
        <td>+10</td>
        <td>+10</td>
        <td><a href="#Energie-fokussieren">Energie fokussieren 9W6</a></td>
        <td>4</td>
        <td>4+1</td>
        <td>4+1</td>
        <td>4+1</td>
        <td>4+1</td>
        <td>4+1</td>
        <td>4+1</td>
        <td>3+1</td>
        <td>2+1</td>
        <td>1+1</td>
    </tr>
    <tr>
        <td>18</td>
        <td>+13/+8/+3</td>
        <td>+6</td>
        <td>+11</td>
        <td>+11</td>
        <td>-</td>
        <td>4</td>
        <td>4+1</td>
        <td>4+1</td>
        <td>4+1</td>
        <td>4+1</td>
        <td>4+1</td>
        <td>4+1</td>
        <td>3+1</td>
        <td>3+1</td>
        <td>2+1</td>
    </tr>
    <tr>
        <td>19</td>
        <td>+14/+9/+4</td>
        <td>+6</td>
        <td>+11</td>
        <td>+11</td>
        <td><a href="#Energie-fokussieren">Energie fokussieren 10W6</a></td>
        <td>4</td>
        <td>4+1</td>
        <td>4+1</td>
        <td>4+1</td>
        <td>4+1</td>
        <td>4+1</td>
        <td>4+1</td>
        <td>4+1</td>
        <td>3+1</td>
        <td>3+1</td>
    </tr>
    <tr>
        <td>20</td>
        <td>+15/+10/+5</td>
        <td>+6</td>
        <td>+12</td>
        <td>+12</td>
        <td>-</td>
        <td>4</td>
        <td>4+1</td>
        <td>4+1</td>
        <td>4+1</td>
        <td>4+1</td>
        <td>4+1</td>
        <td>4+1</td>
        <td>4+1</td>
        <td>4+1</td>
        <td>4+1</td>
    </tr>
    <tr>
            <td colspan="16">Hinweis: „+1“ repräsentiert den Domänenzauberplatz</td>
    </tr>
</table>

<?php require '../../pagxpiedo.php' ?>

