<?php require '../../pagxkapo.php' ?>

<h1>Sorĉisto</h1>
<table>
<tr>
<th rowspan="2">Nivelo
<th rowspan="2">BAB</th>
<th rowspan="2">REF</th>
<th rowspan="2">VOL</th>
<th rowspan="2">PER</th>
<th rowspan="2">Speciala</th>
<th class="sen-sub-linio" colspan="9">Sorĉoj po tago</th>
</th></tr>
<tr>
<th>1a</th>
<th>2a</th>
<th>3a</th>
<th>4a</th>
<th>5a</th>
<th>6a</th>
<th>7a</th>
<th>8a</th>
<th>9a</th>
</tr>
    <td>1</td>
    <td>+0</td>
    <td>+0</td>
    <td>+2</td>
    <td>+0</td>
    <td><a href="#Blutlinien">Macht des Blutes</a>, <a href="#Zaubertricks">Zaubertricks</a>, <a href="#Materialkomponentenlos-zaubern">Materialkomponentenlos zaubern</a></td>
    <td>3</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>

<tr>
    <td>2</td>
    <td>+1</td>
    <td>+0</td>
    <td>+3</td>
    <td>+0</td>
    <td>-</td>
    <td>4</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
</tr>
<tr>
    <td>3</td>
    <td>+1</td>
    <td>+1</td>
    <td>+3</td>
    <td>+1</td>
    <td><a href="#Blutlinien">Macht des Blutes</a>, <a href="#Blutlinien">Zauber des Blutes</a></td>
    <td>5</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
</tr>
<tr>
    <td>4</td>
    <td>+2</td>
    <td>+1</td>
    <td>+4</td>
    <td>+1</td>
    <td>-</td>
    <td>6</td>
    <td>3</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
</tr>
<tr>
    <td>5</td>
    <td>+2</td>
    <td>+1</td>
    <td>+4</td>
    <td>+1</td>
    <td><a href="#Blutlinien">Zauber des Blutes</a></td>
    <td>6</td>
    <td>4</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
</tr>
<tr>
    <td>6</td>
    <td>+3</td>
    <td>+2</td>
    <td>+5</td>
    <td>+2</td>
    <td>-</td>
    <td>6</td>
    <td>5</td>
    <td>3</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
</tr>
<tr>
    <td>7</td>
    <td>+3</td>
    <td>+2</td>
    <td>+5</td>
    <td>+2</td>
    <td><a href="#Blutlinien">Talent des Blutes</a>, <a href="#Blutlinien">Zauber des Blutes</a></td>
    <td>6</td>
    <td>6</td>
    <td>4</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
</tr>
<tr>
    <td>8</td>
    <td>+4</td>
    <td>+2</td>
    <td>+6</td>
    <td>+2</td>
    <td>-</td>
    <td>6</td>
    <td>6</td>
    <td>5</td>
    <td>3</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
</tr>
<tr>
    <td>9</td>
    <td>+4</td>
    <td>+3</td>
    <td>+6</td>
    <td>+3</td>
    <td><a href="#Blutlinien">Macht des Blutes</a>, <a href="#Blutlinien">Zauber des Blutes</a></td>
    <td>6</td>
    <td>6</td>
    <td>6</td>
    <td>4</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
</tr>
<tr>
    <td>10</td>
    <td>+5</td>
    <td>+3</td>
    <td>+7</td>
    <td>+3</td>
    <td>-</td>
    <td>6</td>
    <td>6</td>
    <td>6</td>
    <td>5</td>
    <td>3</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
</tr>
<tr>
    <td>11</td>
    <td>+5</td>
    <td>+3</td>
    <td>+7</td>
    <td>+3</td>
    <td><a href="#Blutlinien">Zauber des Blutes</a></td>
    <td>6</td>
    <td>6</td>
    <td>6</td>
    <td>6</td>
    <td>4</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
</tr>
<tr>
    <td>12</td>
    <td>+6/+1</td>
    <td>+4</td>
    <td>+8</td>
    <td>+4</td>
    <td>-</td>
    <td>6</td>
    <td>6</td>
    <td>6</td>
    <td>6</td>
    <td>5</td>
    <td>3</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
</tr>
<tr>
    <td>13</td>
    <td>+6/+1</td>
    <td>+4</td>
    <td>+8</td>
    <td>+4</td>
    <td><a href="#Blutlinien">Talent des Blutes</a>, <a href="#Blutlinien">Zauber des Blutes</a></td>
    <td>6</td>
    <td>6</td>
    <td>6</td>
    <td>6</td>
    <td>6</td>
    <td>4</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
</tr>
<tr>
    <td>14</td>
    <td>+7/+2</td>
    <td>+4</td>
    <td>+9</td>
    <td>+4</td>
    <td>-</td>
    <td>6</td>
    <td>6</td>
    <td>6</td>
    <td>6</td>
    <td>6</td>
    <td>5</td>
    <td>3</td>
    <td>-</td>
    <td>-</td>
</tr>
<tr>
    <td>15</td>
    <td>+7/+2</td>
    <td>+5</td>
    <td>+9</td>
    <td>+5</td>
    <td><a href="#Blutlinien">Macht des Blutes</a>, <a href="#Blutlinien">Zauber des Blutes</a></td>
    <td>6</td>
    <td>6</td>
    <td>6</td>
    <td>6</td>
    <td>6</td>
    <td>6</td>
    <td>4</td>
    <td>-</td>
    <td>-</td>
</tr>
<tr>
    <td>16</td>
    <td>+8/+3</td>
    <td>+5</td>
    <td>+10</td>
    <td>+5</td>
    <td>-</td>
    <td>6</td>
    <td>6</td>
    <td>6</td>
    <td>6</td>
    <td>6</td>
    <td>6</td>
    <td>5</td>
    <td>3</td>
    <td>-</td>
</tr>
<tr>
    <td>17</td>
    <td>+8/+3</td>
    <td>+5</td>
    <td>+10</td>
    <td>+5</td>
    <td>-<a href="#Blutlinien">Zauber des Blutes</a></td>
    <td>6</td>
    <td>6</td>
    <td>6</td>
    <td>6</td>
    <td>6</td>
    <td>6</td>
    <td>6</td>
    <td>4</td>
    <td>-</td>
</tr>
<tr>
    <td>18</td>
    <td>+9/+4</td>
    <td>+6</td>
    <td>+11</td>
    <td>+6</td>
    <td>-</td>
    <td>6</td>
    <td>6</td>
    <td>6</td>
    <td>6</td>
    <td>6</td>
    <td>6</td>
    <td>6</td>
    <td>5</td>
    <td>3</td>
</tr>
<tr>
    <td>19</td>
    <td>+9/+4</td>
    <td>+6</td>
    <td>+11</td>
    <td>+6</td>
    <td><a href="#Blutlinien">Talent des Blutes</a>, <a href="#Blutlinien">Zauber des Blutes</a></td>
    <td>6</td>
    <td>6</td>
    <td>6</td>
    <td>6</td>
    <td>6</td>
    <td>6</td>
    <td>6</td>
    <td>6</td>
    <td>4</td>
</tr>
<tr>
    <td>20</td>
    <td>+10/+5</td>
    <td>+6</td>
    <td>+12</td>
    <td>+6</td>
    <td><a href="#Blutlinien">Macht des Blutes</a></td>
    <td>6</td>
    <td>6</td>
    <td>6</td>
    <td>6</td>
    <td>6</td>
    <td>6</td>
    <td>6</td>
    <td>6</td>
    <td>6</td>
</tr>
</table>

<?php require '../../pagxpiedo.php' ?>

